version: "3.8"

services:
  mongo:
    image: hub.hamdocker.ir/library/mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chatroom:
    build: .
    container_name: chat-room
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017

volumes:
  mongo_data:
